export const BUTTON_STYLES = [
  { value: 'link', label: 'Link' },
  { value: 'blurple', label: 'Blurple' },
  { value: 'green', label: 'Green' },
  { value: 'grey', label: 'Grey' },
  { value: 'red', label: 'Red' },
]

export const BUTTON_STYLE_COLORS: Record<string, string> = {
  link: '#4f545c',
  blurple: '#5865f2',
  blue: '#5865f2',
  primary: '#5865f2',
  green: '#57f287',
  success: '#57f287',
  grey: '#4f545c',
  gray: '#4f545c',
  secondary: '#4f545c',
  red: '#ed4245',
  danger: '#ed4245',
}

export const VARIABLES = [
  { category: 'User', vars: [
    { name: '{user}', desc: 'Username' },
    { name: '{user.id}', desc: 'User ID' },
    { name: '{user.name}', desc: 'Username' },
    { name: '{user.mention}', desc: 'User mention' },
    { name: '{user.avatar}', desc: 'Avatar URL' },
    { name: '{user.display_avatar}', desc: 'Display avatar URL' },
    { name: '{user.display_name}', desc: 'Display name' },
    { name: '{user.discriminator}', desc: 'Discriminator tag' },
    { name: '{user.created_at}', desc: 'Account creation date' },
    { name: '{user.created_at_timestamp}', desc: 'Creation timestamp' },
    { name: '{user.bot}', desc: 'Whether user is a bot' },
    { name: '{user.joined_at}', desc: 'Server join date' },
    { name: '{user.joined_at_timestamp}', desc: 'Join timestamp' },
    { name: '{user.boost}', desc: 'Whether user is boosting' },
    { name: '{user.boost_since}', desc: 'Boost start date' },
    { name: '{user.color}', desc: 'Role color hex' },
    { name: '{user.top_role}', desc: 'Highest role name' },
    { name: '{user.role_list}', desc: 'Comma-separated roles' },
    { name: '{user.join_position}', desc: 'Join position number' },
    { name: '{user.join_position_suffix}', desc: 'Join position with suffix' },
    { name: '{user.guild_avatar}', desc: 'Server-specific avatar' },
  ]},
  { category: 'Server', vars: [
    { name: '{guild.name}', desc: 'Server name' },
    { name: '{guild.id}', desc: 'Server ID' },
    { name: '{guild.count}', desc: 'Member count' },
    { name: '{guild.icon}', desc: 'Server icon URL' },
    { name: '{guild.banner}', desc: 'Server banner URL' },
    { name: '{guild.boost_count}', desc: 'Number of boosts' },
    { name: '{guild.boost_tier}', desc: 'Boost level (0-3)' },
    { name: '{guild.owner_id}', desc: 'Owner user ID' },
    { name: '{guild.created_at}', desc: 'Server creation date' },
    { name: '{guild.emoji_count}', desc: 'Number of emojis' },
    { name: '{guild.role_count}', desc: 'Number of roles' },
    { name: '{guild.channels_count}', desc: 'Number of channels' },
    { name: '{guild.shard}', desc: 'Shard ID' },
    { name: '{guild.owner.mention}', desc: 'Owner mention' },
    { name: '{guild.owner.name}', desc: 'Owner username' },
  ]},
  { category: 'Channel', vars: [
    { name: '{channel.name}', desc: 'Channel name' },
    { name: '{channel.id}', desc: 'Channel ID' },
    { name: '{channel.mention}', desc: 'Channel mention' },
    { name: '{channel.type}', desc: 'Channel type' },
    { name: '{channel.topic}', desc: 'Channel topic' },
    { name: '{channel.position}', desc: 'Position in list' },
    { name: '{channel.category_name}', desc: 'Parent category name' },
    { name: '{channel.slowmode_delay}', desc: 'Slowmode in seconds' },
  ]},
  { category: 'Moderator', vars: [
    { name: '{moderator}', desc: 'Moderator mention' },
    { name: '{moderator.mention}', desc: 'Moderator mention' },
    { name: '{moderator.name}', desc: 'Moderator username' },
    { name: '{moderator.display_name}', desc: 'Moderator display name' },
    { name: '{moderator.id}', desc: 'Moderator user ID' },
    { name: '{moderator.avatar}', desc: 'Moderator avatar URL' },
    { name: '{moderator.display_avatar}', desc: 'Moderator display avatar' },
    { name: '{moderator.discriminator}', desc: 'Moderator discriminator' },
    { name: '{moderator.created_at}', desc: 'Moderator creation date' },
    { name: '{moderator.created_at_timestamp}', desc: 'Moderator creation timestamp' },
    { name: '{reason}', desc: 'Action reason' },
  ]},
]
